import "./globals.css";

export const metadata = {
  title: "Athletics Hub",
  description: "Generated by create next app",
  icons: {
    icon: "./icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
